### ISSUE TITLE
Broken on windows

### ISSUE THREAD

**Issue by ugexe** [azawawi/perl6-file-homedir#4]
ping @sdondley -- https://ci.appveyor.com/project/azawawi/raku-file-homedir-kveko/builds/44860869#L1305

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/raku-file-homedir/commit/9ff6b6eeca2af585dfc2d56a8801b14100ceca25. Also GitHub test workflow is now working.

@ugexe  Thanks. I am warming up 👍
