### ISSUE TITLE
Broken on macOS

### ISSUE THREAD

**Issue by ugexe** [azawawi/perl6-file-homedir#5]
ping @sdondley 

https://github.com/azawawi/raku-file-homedir/blob/c635ebb5333a519b5a43cbb6e84ae9193dd57c32/lib/File/HomeDir.rakumod#L15

https://github.com/azawawi/raku-file-homedir/blob/c635ebb5333a519b5a43cbb6e84ae9193dd57c32/META6.json#L10

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/raku-file-homedir/commit/9ff6b6eeca2af585dfc2d56a8801b14100ceca25. Also GitHub test workflow is now working on all platforms.

@ugexe  Thanks. 👍
